name: Build Windows

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: zed

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: cd zed && cargo build --release

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: build-windows
        path: zed/target/release/
